### ISSUE TITLE
Bot bugs out for some reason when sending a message sometimes.

### ISSUE THREAD

**Issue by Rijndael1998** [DeguSec/Rchan#21]
```
/home/r/Documents/Git/Rchan/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498
				throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
          ^
```
```ts
DiscordAPIError[50007]: Cannot send messages to this user
    at SequentialHandler.runRequest (/home/r/Documents/Git/Rchan/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/r/Documents/Git/Rchan/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:198:11)
    at async REST.request (/home/r/Documents/Git/Rchan/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at async DMChannel.send (/home/r/Documents/Git/Rchan/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
  requestBody: {
    files: [],
    json: {
      content: "Okay, dude. I'm sorry if I'm bothering you. I'll stop talking now. If you change your mind and want to chat, just let me know. Peace out.",
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: [Object],
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Cannot send messages to this user', code: 50007 },
  code: 50007,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1083901252326404116/messages'
}
```

**Comment by Rijndael1998** [comment]
I have not seen this happen since. Will reopen if happens again. Closing.
